<?php

namespace App\Observers;

use App\Models\UmrahJamaah;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class BookingUmrahObserver
{
    /**
     * Handle the UmrahJamaah "created" event.
     */
    public function created(UmrahJamaah $umrahJamaah): void
    {
        Log::info('Booking Umrah Created: ' . $umrahJamaah->id);

        $jamaah = $umrahJamaah->load('user', 'umrahSchedule.umrahPackage');

        try {
            $gender_calling = '';
            if($umrahJamaah->gender == "laki-laki"){
                $gender_calling = "Bapak";
            }else{
                $gender_calling = "Ibu";
            }
            $response_wa = Http::post(env('WHATSAPP_API_URL')  . "/send-message", [
                'session' => env('WHATSAPP_API_SESSION'),
                'to' => whatsappNumber($umrahJamaah->phone),
                'text' => "Assalamu'alaikum" . $gender_calling . " " . $umrahJamaah->name . ",\n\n" .
                    "Terima kasih telah mempercayakan kami menjadi mitra perjalanan ibadah umroh Anda. kami senang dapat membantu Anda dalam merencanakan perjalanan ibadah umroh Anda.\n" .
                    "anda telah terdaftar sebagai jamaah umroh dengan ID *" . $umrahJamaah->code . "*.\n\n" . "oleh agen/staf kami *" . $umrahJamaah->user->name . "*.\n\n" .
                    "Terima Kasih.\n\n" .
                    "_Generated by system: " . env('APP_NAME') . "_"

            ]);

            if ($response_wa->status() == 200) {
                Log::info('Notification sent successfully');
            } else {
                Log::error('Error sending notification: ' . $response_wa->body());
            }
        } catch (\Throwable $th) {
            //throw $th;
        }
    }

    /**
     * Handle the UmrahJamaah "updated" event.
     */
    public function updated(UmrahJamaah $umrahJamaah): void
    {
        //
    }

    /**
     * Handle the UmrahJamaah "deleted" event.
     */
    public function deleted(UmrahJamaah $umrahJamaah): void
    {
        //
    }

    /**
     * Handle the UmrahJamaah "restored" event.
     */
    public function restored(UmrahJamaah $umrahJamaah): void
    {
        //
    }

    /**
     * Handle the UmrahJamaah "force deleted" event.
     */
    public function forceDeleted(UmrahJamaah $umrahJamaah): void
    {
        //
    }
}
